url: https://y7kim.github.io
baseurl: /ucl-photonics-society/

# Site settings
title: UCL Photonics Society
email: photonics.society@ucl.ac.uk
description: "UCL Photonics Society is a student-led society at University College London (UCL) that aims to bring together students and professionals interested in the field of photonics. We organize events, workshops, and networking opportunities to foster learning and collaboration within the photonics community."


# Team names, titles and social links
people:
- name: David Gerard
  pic: 1
  position: President
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/david-gerard-cu/
    - title: github
      url: https://github.com/David-GERARD


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/company/ucl-photonics-society/
  - title: github
    url: https://github.com/UCL-Photonics-Society
  - title: instagram
    url: https://www.instagram.com/ucl.photonicssociety/

# Postal address (add as many lines as necessary)
address:
  - line: University College London,
  - line: Gower Street, London WC1E 6BT, United Kingdom

# Build settings
markdown: kramdown
permalink: pretty